algo = input('Digite qualquer coisa: ')
print('{} é um espaço:'.format(algo), algo.isspace())
print('{} está em maiúsculo(a):'.format(algo), algo.isupper())
print('{} está em minúsculo(a):'.format(algo), algo.islower())
print('{} faz parte do alfabéto:'.format(algo), algo.isalpha())
print('{} é um titulo:'.format(algo), algo.istitle())
print('{} faz parte do ascii:'.format(algo), algo.isascii())
print('{} é um número:'.format(algo), algo.isnumeric())
print('{} é alfanumérico:'.format(algo), algo.isalnum())
print('{} é um número decimal:'.format(algo), algo.isdecimal())
print('{} é um digito:'.format(algo), algo.isdigit())
print('{} é um identificador:'.format(algo), algo.isidentifier())
print('{} pode ser impresso:'.format(algo), algo.isprintable())
